# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=post.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='textpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_post_title', models.CharField(max_length=500)),
                ('text_post_content', models.CharField(max_length=9999999)),
                ('comments_select', models.BooleanField(default=True)),
                ('comments_text', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pictureupload', models.ImageField(blank=True, height_field='height_field', upload_to=post.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=100, null=True)),
                ('width_field', models.IntegerField(blank=True, default=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_stamp', '-date_updated'],
            },
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.textpost'),
        ),
    ]
